using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace RestaurantBillingSystem
{
    public class Bill : IComparable<Bill>
    {
        private DateTime date;
        private int invoiceNum; //number is autogenerated based on last invoice on the stack
        private string tableName;
        private string custName;
        private string custType;
        private PaymentType paymentType;
        private decimal totalAmt;
        private decimal tipAmount = 0.00m;

        public DateTime Date { get => date; set => date = value; }
        public int InvoiceNum { get => invoiceNum; set => invoiceNum = value; }
        public string TableName { get => tableName; set => tableName = value; }
        public string CustName { get => custName; set => custName = value; }
        public string CustType { get => custType; set => custType = value; }
        public PaymentType PaymentType { get => paymentType; set => paymentType = value; }
        public decimal TotalAmt { get => totalAmt; set => totalAmt = value; }
        public decimal TipAmount { get => tipAmount; set => tipAmount = value; }

        public int CompareTo(Bill other)
        {
            return this.invoiceNum.CompareTo(other.InvoiceNum) * -1;
        }

        public override string ToString()
        {
            return TipAmount.ToString() + ", " + InvoiceNum.ToString() + "\n";
        }
    }
}
